package forms;

import ahorcado.Main;
import enumerados.Dificultad;
import excepciones.GanaJuego;
import java.awt.Color;
import java.awt.Container;
import java.awt.GridLayout;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import java.util.Collection;
import java.util.Collections;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

public class FormInicial extends javax.swing.JFrame
{

    //<editor-fold defaultstate="collapsed" desc="Autogenerado">
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jpInicio = new javax.swing.JPanel();
        btnJugar = new javax.swing.JButton();
        btnDificil = new javax.swing.JToggleButton();
        btnNormal = new javax.swing.JToggleButton();
        btnFacil = new javax.swing.JToggleButton();
        jpGameplay = new javax.swing.JPanel();
        jpUsuario = new javax.swing.JPanel();
        jpRank = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnOK = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        mnMenu = new javax.swing.JMenu();
        mnItemNuevo = new javax.swing.JMenuItem();
        mnItemRank = new javax.swing.JMenuItem();
        mnItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ahorcado"); // NOI18N
        setMinimumSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        jpInicio.setAlignmentX(0.0F);
        jpInicio.setAlignmentY(0.0F);
        jpInicio.setMaximumSize(null);
        jpInicio.setOpaque(false);
        jpInicio.setPreferredSize(new java.awt.Dimension(800, 600));

        btnJugar.setAlignmentY(0.0F);
        btnJugar.setBorderPainted(false);
        btnJugar.setContentAreaFilled(false);
        btnJugar.setFocusPainted(false);
        btnJugar.setMaximumSize(new java.awt.Dimension(143, 71));
        btnJugar.setMinimumSize(new java.awt.Dimension(143, 71));
        btnJugar.setPreferredSize(new java.awt.Dimension(143, 71));
        btnJugar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnJugarActionPerformed(evt);
            }
        });

        btnDificil.setBorderPainted(false);
        btnDificil.setContentAreaFilled(false);
        btnDificil.setFocusPainted(false);
        btnDificil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDificil.setMaximumSize(new java.awt.Dimension(198, 142));
        btnDificil.setMinimumSize(new java.awt.Dimension(198, 142));
        btnDificil.setPreferredSize(new java.awt.Dimension(198, 142));
        btnDificil.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnDificilActionPerformed(evt);
            }
        });

        btnNormal.setBorderPainted(false);
        btnNormal.setContentAreaFilled(false);
        btnNormal.setFocusPainted(false);
        btnNormal.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNormal.setMaximumSize(new java.awt.Dimension(198, 142));
        btnNormal.setMinimumSize(new java.awt.Dimension(198, 142));
        btnNormal.setPreferredSize(new java.awt.Dimension(198, 142));
        btnNormal.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnNormalActionPerformed(evt);
            }
        });

        btnFacil.setBorderPainted(false);
        btnFacil.setContentAreaFilled(false);
        btnFacil.setFocusPainted(false);
        btnFacil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFacil.setMaximumSize(new java.awt.Dimension(198, 142));
        btnFacil.setMinimumSize(new java.awt.Dimension(198, 142));
        btnFacil.setPreferredSize(new java.awt.Dimension(198, 142));
        btnFacil.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnFacilActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpInicioLayout = new javax.swing.GroupLayout(jpInicio);
        jpInicio.setLayout(jpInicioLayout);
        jpInicioLayout.setHorizontalGroup(
            jpInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInicioLayout.createSequentialGroup()
                .addGroup(jpInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpInicioLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(btnFacil, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNormal, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDificil, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jpInicioLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(btnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        jpInicioLayout.setVerticalGroup(
            jpInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpInicioLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jpInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFacil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNormal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDificil, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpGameplay.setAlignmentX(0.0F);
        jpGameplay.setAlignmentY(0.0F);
        jpGameplay.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jpGameplay.setMaximumSize(null);
        jpGameplay.setOpaque(false);
        jpGameplay.setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout jpGameplayLayout = new javax.swing.GroupLayout(jpGameplay);
        jpGameplay.setLayout(jpGameplayLayout);
        jpGameplayLayout.setHorizontalGroup(
            jpGameplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jpGameplayLayout.setVerticalGroup(
            jpGameplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jpUsuario.setOpaque(false);

        javax.swing.GroupLayout jpUsuarioLayout = new javax.swing.GroupLayout(jpUsuario);
        jpUsuario.setLayout(jpUsuarioLayout);
        jpUsuarioLayout.setHorizontalGroup(
            jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jpUsuarioLayout.setVerticalGroup(
            jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jpRank.setMaximumSize(null);
        jpRank.setOpaque(false);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setOpaque(false);
        jScrollPane1.setViewportView(jTextArea1);

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpRankLayout = new javax.swing.GroupLayout(jpRank);
        jpRank.setLayout(jpRankLayout);
        jpRankLayout.setHorizontalGroup(
            jpRankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpRankLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
            .addGroup(jpRankLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpRankLayout.setVerticalGroup(
            jpRankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpRankLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnOK)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        mnMenu.setMnemonic('J');
        mnMenu.setText("Juego");

        mnItemNuevo.setMnemonic('N');
        mnItemNuevo.setText("Nuevo");
        mnItemNuevo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnItemNuevoActionPerformed(evt);
            }
        });
        mnMenu.add(mnItemNuevo);

        mnItemRank.setMnemonic('R');
        mnItemRank.setText("Ranking");
        mnItemRank.setToolTipText("");
        mnItemRank.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnItemRankActionPerformed(evt);
            }
        });
        mnMenu.add(mnItemRank);

        mnItemSalir.setMnemonic('S');
        mnItemSalir.setText("Salir");
        mnItemSalir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnItemSalirActionPerformed(evt);
            }
        });
        mnMenu.add(mnItemSalir);

        menuBar.add(mnMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jpInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpGameplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpRank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(164, Short.MAX_VALUE)
                .addComponent(jpInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpGameplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpRank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnItemSalirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnItemSalirActionPerformed
    {//GEN-HEADEREND:event_mnItemSalirActionPerformed
        System.exit(NORMAL);
    }//GEN-LAST:event_mnItemSalirActionPerformed

    private void mnItemNuevoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnItemNuevoActionPerformed
    {//GEN-HEADEREND:event_mnItemNuevoActionPerformed
        //llama al evento de presionar btnJugar
        btnJugarActionPerformed(evt);
    }//GEN-LAST:event_mnItemNuevoActionPerformed

    private void mnItemRankActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnItemRankActionPerformed
    {//GEN-HEADEREND:event_mnItemRankActionPerformed
        jpInicio.setVisible(false);
        jpGameplay.setVisible(false);
        jpUsuario.setVisible(false);
        lanzarRanking();
    }//GEN-LAST:event_mnItemRankActionPerformed

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnJugarActionPerformed
    {//GEN-HEADEREND:event_btnJugarActionPerformed

        this.jpInicio.setVisible(false);

        try
        {
            //iniciar nuevo juego
            Main.backend.nuevoJuego();

            //panel de la partida
            empezarJuego();
        }
        catch (GanaJuego ex)
        {
            //pedirUsuario();
            JOptionPane.showMessageDialog(null, "GANASTE");

        }

    }//GEN-LAST:event_btnJugarActionPerformed

    private void btnDificilActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnDificilActionPerformed
    {//GEN-HEADEREND:event_btnDificilActionPerformed
        //botones
        this.btnFacil.setIcon(new ImageIcon("niveles-05.png"));
        this.btnNormal.setIcon(new ImageIcon("niveles-06.png"));
        this.btnDificil.setIcon(new ImageIcon("niveles-04.png"));

        btnFacil.setSelected(false);
        btnNormal.setSelected(false);
        btnDificil.setSelected(true);

        Main.backend.setDificultad(Dificultad.Dificil);
        btnJugar.setEnabled(true);

    }//GEN-LAST:event_btnDificilActionPerformed

    private void btnNormalActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnNormalActionPerformed
    {//GEN-HEADEREND:event_btnNormalActionPerformed
        //botones
        this.btnFacil.setIcon(new ImageIcon("niveles-05.png"));
        this.btnNormal.setIcon(new ImageIcon("niveles-03.png"));
        this.btnDificil.setIcon(new ImageIcon("niveles-07.png"));

        btnFacil.setSelected(false);
        btnNormal.setSelected(true);
        btnDificil.setSelected(false);

        Main.backend.setDificultad(Dificultad.Normal);
        btnJugar.setEnabled(true);
    }//GEN-LAST:event_btnNormalActionPerformed

    private void btnFacilActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnFacilActionPerformed
    {//GEN-HEADEREND:event_btnFacilActionPerformed
        //botones
        this.btnFacil.setIcon(new ImageIcon("niveles-02.png"));
        this.btnNormal.setIcon(new ImageIcon("niveles-06.png"));
        this.btnDificil.setIcon(new ImageIcon("niveles-07.png"));

        btnFacil.setSelected(true);
        btnNormal.setSelected(false);
        btnDificil.setSelected(false);

        Main.backend.setDificultad(Dificultad.Facil);
        btnJugar.setEnabled(true);

    }//GEN-LAST:event_btnFacilActionPerformed

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnOKActionPerformed
    {//GEN-HEADEREND:event_btnOKActionPerformed
        this.jpRank.setVisible(false);
    }//GEN-LAST:event_btnOKActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnDificil;
    private javax.swing.JToggleButton btnFacil;
    private javax.swing.JButton btnJugar;
    private javax.swing.JToggleButton btnNormal;
    private javax.swing.JButton btnOK;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel jpGameplay;
    private javax.swing.JPanel jpInicio;
    private javax.swing.JPanel jpRank;
    private javax.swing.JPanel jpUsuario;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnItemNuevo;
    private javax.swing.JMenuItem mnItemRank;
    private javax.swing.JMenuItem mnItemSalir;
    private javax.swing.JMenu mnMenu;
    // End of variables declaration//GEN-END:variables

//</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="Atributos">
    Container contenedor;
    ComponentListener listenerVolverAInicio;
    PanelJuego jugar;

    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="Constructor">
    public FormInicial()
    {
        this.setContentPane(new JLabel(new ImageIcon("fondo-01.png")));
        initComponents();
        btnJugar.setEnabled(false);
        this.jpRank.setVisible(false);
        //   contenedor = new Container();
        listenerVolverAInicio = new ComponentListener()
        {
            @Override
            public void componentResized(ComponentEvent e)
            {

            }

            @Override
            public void componentMoved(ComponentEvent e)
            {

            }

            @Override
            public void componentShown(ComponentEvent e)
            {

            }

            @Override
            public void componentHidden(ComponentEvent e)
            {
                jpInicio.setVisible(false);
                jpGameplay.setVisible(false);
                jpUsuario.setVisible(false);
                lanzarRanking();
            }

        };

        this.btnFacil.setIcon(new ImageIcon("niveles-05.png"));
        this.btnNormal.setIcon(new ImageIcon("niveles-06.png"));
        this.btnDificil.setIcon(new ImageIcon("niveles-07.png"));

        this.btnJugar.setDisabledIcon(new ImageIcon("jugar-08.png"));
        this.btnJugar.setIcon(new ImageIcon("jugar-09.png"));
        this.btnJugar.setRolloverIcon(new ImageIcon("jugar-11.png"));
        this.btnJugar.setPressedIcon(new ImageIcon("jugar-10.png"));
    }

    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="Metodos">
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FormInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FormInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FormInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FormInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new FormInicial().setVisible(true);
            }

        });
    }

    private void empezarJuego()
    {
        if (contenedor != null)
        {
            contenedor.removeAll();
        }
        contenedor = jpGameplay;
        contenedor.setLayout(new GridLayout(1, 1));

        this.jpGameplay.setVisible(true);

        jugar = new PanelJuego();
        jugar.addComponentListener(listenerVolverAInicio);

        contenedor.add(jugar);

    }

    private void lanzarRanking()
    {

        jScrollPane1.setBackground(new Color(0, 0, 0));
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);

        this.jpRank.addComponentListener(new ComponentListener()
        {
            @Override
            public void componentResized(ComponentEvent e)
            {
                //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void componentMoved(ComponentEvent e)
            {
                //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void componentShown(ComponentEvent e)
            {
                // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }

            @Override
            public void componentHidden(ComponentEvent e)
            {
                if (Main.backend.isPartidaEnCurso())
                {
                    jpInicio.setVisible(false);
                    jpGameplay.setVisible(true);
                }
                else
                {
                    jpInicio.setVisible(true);
                    jpGameplay.setVisible(false);
                }
                jpUsuario.setVisible(false);
                jpRank.setVisible(false);
            }
        });

        jTextArea1.setFont(new java.awt.Font("Courier New", 1, 16));
        jTextArea1.setForeground(Color.white);
        jTextArea1.setText(Main.backend.getSortedRanking().toString());
        this.setLocationRelativeTo(null);
        this.jpRank.setVisible(true);

    }

    //</editor-fold>
}
