package forms;

import ahorcado.Main;
import excepciones.GanaJuego;
import excepciones.GanaPartida;
import excepciones.PierdePartida;
import java.awt.Color;
import java.awt.Container;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import toolbox.Cadena;

public class PanelJuego extends javax.swing.JPanel
{

    //<editor-fold defaultstate="collapsed" desc="Autogenerado">
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        panelTeclado = new javax.swing.JPanel();
        panelImagen = new javax.swing.JPanel();
        panelPalabra = new javax.swing.JPanel();
        lblPuntos = new javax.swing.JLabel();
        lblPuntos1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(791, 536));
        setMinimumSize(new java.awt.Dimension(791, 536));
        setOpaque(false);
        addComponentListener(new java.awt.event.ComponentAdapter()
        {
            public void componentShown(java.awt.event.ComponentEvent evt)
            {
                formComponentShown(evt);
            }
        });

        panelTeclado.setMaximumSize(new java.awt.Dimension(443, 227));
        panelTeclado.setMinimumSize(new java.awt.Dimension(443, 227));
        panelTeclado.setOpaque(false);
        panelTeclado.setPreferredSize(new java.awt.Dimension(443, 227));

        javax.swing.GroupLayout panelTecladoLayout = new javax.swing.GroupLayout(panelTeclado);
        panelTeclado.setLayout(panelTecladoLayout);
        panelTecladoLayout.setHorizontalGroup(
            panelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );
        panelTecladoLayout.setVerticalGroup(
            panelTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 227, Short.MAX_VALUE)
        );

        panelImagen.setMaximumSize(new java.awt.Dimension(300, 360));
        panelImagen.setMinimumSize(new java.awt.Dimension(300, 360));
        panelImagen.setPreferredSize(new java.awt.Dimension(300, 361));

        javax.swing.GroupLayout panelImagenLayout = new javax.swing.GroupLayout(panelImagen);
        panelImagen.setLayout(panelImagenLayout);
        panelImagenLayout.setHorizontalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        panelImagenLayout.setVerticalGroup(
            panelImagenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 361, Short.MAX_VALUE)
        );

        panelPalabra.setBackground(new java.awt.Color(255, 255, 255));
        panelPalabra.setMaximumSize(new java.awt.Dimension(749, 50));
        panelPalabra.setMinimumSize(new java.awt.Dimension(749, 50));
        panelPalabra.setPreferredSize(new java.awt.Dimension(749, 50));

        javax.swing.GroupLayout panelPalabraLayout = new javax.swing.GroupLayout(panelPalabra);
        panelPalabra.setLayout(panelPalabraLayout);
        panelPalabraLayout.setHorizontalGroup(
            panelPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 749, Short.MAX_VALUE)
        );
        panelPalabraLayout.setVerticalGroup(
            panelPalabraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        lblPuntos.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblPuntos.setForeground(new java.awt.Color(255, 255, 255));
        lblPuntos.setText("PUNTOS: ");

        lblPuntos1.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        lblPuntos1.setForeground(new java.awt.Color(255, 255, 255));
        lblPuntos1.setText("PUNTOS: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panelTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPuntos)
                            .addComponent(lblPuntos1))))
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(panelImagen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(lblPuntos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblPuntos1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(panelTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(panelPalabra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(101, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt)//GEN-FIRST:event_formComponentShown
    {//GEN-HEADEREND:event_formComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_formComponentShown

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblPuntos;
    private javax.swing.JLabel lblPuntos1;
    private javax.swing.JPanel panelImagen;
    private javax.swing.JPanel panelPalabra;
    private javax.swing.JPanel panelTeclado;
    // End of variables declaration//GEN-END:variables
    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="Atributos">

    JButton[] botones;
    Container cp;
    JLabel[] letras;
    int easterEgg = 0;

    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="Constructor">
    public PanelJuego()
    {
        botones = new JButton[28];
        initComponents();
        iniciarTeclado();
        actualizarImagen();
        actualizarStats();
        iniciarPalabra();

    }

    //</editor-fold>
    //<editor-fold defaultstate="collapsed" desc="Metodos">
    public void actualizarImagen()
    {
        if (this.panelImagen != null)
        {
            this.panelImagen.removeAll();
        }

        Container cp = this.panelImagen;
        GridLayout gl = new GridLayout(1, 1);
        cp.setLayout(gl);
        String archivoImagen = "meme/meme-" + Cadena.lPad(Integer.toString(Main.backend.getContadorFallos()), 2, "0") + ".jpg";
        System.out.println("imagen: " + archivoImagen);
        ImageIcon intentos = new ImageIcon(archivoImagen);
        JLabel lblImagen = new JLabel(intentos);
        cp.add(lblImagen);
        this.panelImagen.setVisible(false);
        this.panelImagen.setVisible(true);
    }

    public void actualizarStats()
    {
        StringBuilder txt1 = new StringBuilder();

        txt1.append("ACIERTOS: ");
        txt1.append(Main.backend.getContadorAciertos());
        txt1.append(" | ");
        txt1.append("FALLOS: ");
        txt1.append(Main.backend.getContadorFallos());
        txt1.append(" | ");
        txt1.append("INTENTOS RESTANTES: ");
        txt1.append(Main.backend.getMaxFallos() - Main.backend.getContadorFallos());
        this.lblPuntos.setText(txt1.toString());

        StringBuilder txt = new StringBuilder();
        txt.append("PARTIDAS JUGADAS: ");
        txt.append(Main.backend.getUsuario().getPartidasJugadas());
        txt.append(" | ");
        txt.append("PUNTAJE: ");
        txt.append(Main.backend.getUsuario().getPuntajeAcumulado());
        this.lblPuntos1.setText(txt.toString());
    }

    public void iniciarPalabra()
    {
        if (this.panelPalabra != null)
        {
            this.panelPalabra.removeAll();
        }
        Container cp = this.panelPalabra;
        // poner el lenght de la palabra
        GridLayout gl = new GridLayout(1, Main.backend.getPalabra().getTamaño());
        gl.setHgap(2);
        gl.setVgap(2);
        cp.setLayout(gl);
        // hacer un vector del largo de la palabra
        letras = new JLabel[Main.backend.getPalabra().getNombre().length()];

        for (int i = 0; i < letras.length; i++)
        {
            letras[i] = new JLabel();
            cp.add(letras[i]);
            letras[i].setText(" * ");
            letras[i].setForeground(new Color(52, 125, 255));
            letras[i].setHorizontalAlignment((int) CENTER_ALIGNMENT);
            letras[i].setFont(new java.awt.Font("Tahoma", 1, 20));
            letras[i].setVisible(true);
        }

    }

    public void actualizarPalabra()
    {
        for (int i = 0; i < letras.length; i++)
        {
            letras[i].setText(" " + Main.backend.getPalabraSecreta().get(i) + " ");
        }
    }

    public void iniciarTeclado()
    {
        if (this.panelTeclado != null)
        {
            this.panelTeclado.removeAll();
        }

        cp = this.panelTeclado;
        GridLayout gl = new GridLayout(4, 7);
        gl.setHgap(2);
        gl.setVgap(2);
        cp.setLayout(gl);

        //centrar iconos
        for (int i = 0; i < 28; i++)
        {
            if (i < 27)
            {
                botones[i] = new JButton();
                cp.add(botones[i]);
                botones[i].setText(String.valueOf(Main.backend.getAlfabeto().charAt(i)));
                botones[i].setVisible(true);
                botones[i].setForeground(new Color(0, 0, 0));
                botones[i].setFont(new Font("Tahoma", 1, 20));
                botones[i].setBorder(null);
                botones[i].setContentAreaFilled(true);
                botones[i].setFocusPainted(false);

                botones[i].addActionListener(new ActionListener()
                {
                    public void actionPerformed(java.awt.event.ActionEvent evt)
                    {
                        letraClickeada(evt);
                    }

                });
            }
            else
            {
                botones[i] = new JButton();
                cp.add(botones[i]);
                botones[i].setIcon(new ImageIcon("boton-sorpresa-19.jpg"));
                botones[i].setRolloverIcon(new ImageIcon("boton-sorpresa-20.jpg"));
                botones[i].setVisible(true);
                botones[i].setBorder(null);
                botones[i].setContentAreaFilled(true);
                botones[i].setFocusPainted(false);

                botones[i].addActionListener(new ActionListener()
                {
                    public void actionPerformed(java.awt.event.ActionEvent evt)
                    {
                        try
                        {
                            sonido(easterEgg);
                        }
                        catch (Exception e)
                        {

                        }

                    }
                });
            }
        }
    }

    public void letraClickeada(java.awt.event.ActionEvent evt)
    {
        JButton evento = (JButton) evt.getSource();

        Main.backend.setLetraElegida(evento.getText().charAt(0));

        //liberar evento
        evento.setEnabled(false);
        evento.setContentAreaFilled(false);

        //validar letra
        Main.backend.validarLetraElegida();

        //mostrar letras coincidentes
        actualizarPalabra();

        //actualizar imagen
        actualizarImagen();

        //actualizar stats
        actualizarStats();

        try
        {
            //validar partida
            Main.backend.validarEstadoPartida();

            if (!Main.backend.isPistaMostrada() && Main.backend.getContadorFallos() == Main.backend.getMomentoPista())
            {
                FormDialogo pista = new FormDialogo(null, true, Main.backend.getPalabra().getDefinicion(), FormDialogo.TipoRespuesta.Pista);
                pista.setVisible(true);

                Main.backend.setPistaMostrada(true);
            }
        }
        catch (GanaPartida ex)
        {
            FormDialogo ganaste = new FormDialogo(null, true, "F E L I C I T A C I O N E S ! ! !" + "\n" + "Adivinaste la palabra: " + "\n" + Main.backend.getPalabra().getNombre(), FormDialogo.TipoRespuesta.GanaPartida);
            ganaste.setVisible(true);
            if (ganaste.isDialogResult)
            {
                Main.backend.actualizarEstadisticaUsuario(Main.backend.GANA_PARTIDA);

                //pasar siguiente nivel
                limpiarTodo();
            }
        }
        catch (PierdePartida ex)
        {
            FormDialogo perdiste = new FormDialogo(null, true, "La palabra secreta era: " + "\n" + Main.backend.getPalabra().getNombre() + "\n\n" + "PERDISTE!", (Main.backend.getUsuario().getPuntajeUltimo() > 0) ? FormDialogo.TipoRespuesta.PierdePartidaConPuntos : FormDialogo.TipoRespuesta.PierdePartidaSinPuntos);
            perdiste.setVisible(true);
            if (perdiste.isDialogResult)
            {
                Main.backend.actualizarEstadisticaUsuario(Main.backend.PIERDE_PARTIDA);

                //terminar partida
                Main.backend.setPartidaEnCurso(false);

                //volver a inicio
                this.setVisible(false);
            }

        }

    }

    void limpiarTodo()
    {
        try
        {
            Main.backend.nuevaPartida();
            iniciarTeclado();
            actualizarImagen();
            actualizarStats();
            iniciarPalabra();
        }
        catch (GanaJuego ex)
        {
            FormDialogo ganaJuego = new FormDialogo(null, true, "AGOTASTE LAS PALABRAS Y GANASTE EL JUEGO", FormDialogo.TipoRespuesta.GanaJuego);
            ganaJuego.setVisible(true);
            if (ganaJuego.isDialogResult)
            {
                Main.backend.actualizarRanking();
                Main.backend.setPartidaEnCurso(false);

                //volver a inicio
                this.setVisible(false);
            }
        }

    }

    public void sonido(int tipo)
    {
        String archSonido = "musica//shooting_star.wav";
        this.easterEgg++;

        switch (tipo)
        {
            case 0:
                archSonido = "musica//shooting_star.wav";
                break;
            case 1:
                archSonido = "musica//sonido1.wav";
                break;
            case 4:
                archSonido = "musica//sonido4.wav";
                break;
            case 5:
                archSonido = "musica//sonido5.wav";
                break;
            case 6:
                archSonido = "musica/sonido6.wav";
                break;
            default:
                archSonido = "musica//shooting_star.wav";
                break;

        }

        System.out.println("Reproduccir sonido");
        try
        {
            AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(new File(archSonido).getAbsoluteFile());
            Clip clip = AudioSystem.getClip();
            clip.open(audioInputStream);
            clip.start();
        }
        catch (IOException | UnsupportedAudioFileException | LineUnavailableException e)
        {
            System.out.println(e.getMessage());
        }

    }

    //</editor-fold>
}
