package forms;

import ahorcado.Main;
import java.awt.Color;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.MouseListener;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class FormDialogo extends javax.swing.JDialog
{
    //<editor-fold desc="Autogenerado">

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jCheckBox1 = new javax.swing.JCheckBox();
        btnAceptar = new javax.swing.JButton();
        scrollDialogo = new javax.swing.JScrollPane();
        txtMsj = new javax.swing.JTextArea();
        lblReaccion = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();

        jCheckBox1.setText("jCheckBox1");

        setAlwaysOnTop(true);
        setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        setForeground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(349, 228));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        btnAceptar.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.setBorder(null);
        btnAceptar.setBorderPainted(false);
        btnAceptar.setContentAreaFilled(false);
        btnAceptar.setFocusPainted(false);
        btnAceptar.setMaximumSize(new java.awt.Dimension(121, 35));
        btnAceptar.setMinimumSize(new java.awt.Dimension(121, 35));
        btnAceptar.setPreferredSize(new java.awt.Dimension(121, 35));
        btnAceptar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAceptarActionPerformed(evt);
            }
        });

        scrollDialogo.setBorder(null);
        scrollDialogo.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrollDialogo.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        scrollDialogo.setInheritsPopupMenu(true);
        scrollDialogo.setMaximumSize(new java.awt.Dimension(520, 135));
        scrollDialogo.setMinimumSize(new java.awt.Dimension(520, 135));
        scrollDialogo.setName(""); // NOI18N
        scrollDialogo.setOpaque(false);
        scrollDialogo.setPreferredSize(new java.awt.Dimension(520, 135));
        scrollDialogo.setRequestFocusEnabled(false);
        scrollDialogo.setVerifyInputWhenFocusTarget(false);
        scrollDialogo.setWheelScrollingEnabled(false);

        txtMsj.setEditable(false);
        txtMsj.setBackground(new java.awt.Color(35, 44, 105));
        txtMsj.setColumns(20);
        txtMsj.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtMsj.setForeground(new java.awt.Color(255, 255, 255));
        txtMsj.setLineWrap(true);
        txtMsj.setRows(2);
        txtMsj.setToolTipText("");
        txtMsj.setWrapStyleWord(true);
        txtMsj.setAutoscrolls(false);
        txtMsj.setBorder(null);
        txtMsj.setCaretColor(new java.awt.Color(153, 0, 204));
        txtMsj.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        txtMsj.setKeymap(null);
        txtMsj.setMaximumSize(new java.awt.Dimension(259, 80));
        txtMsj.setMinimumSize(new java.awt.Dimension(259, 80));
        txtMsj.setOpaque(false);
        txtMsj.setPreferredSize(new java.awt.Dimension(259, 80));
        txtMsj.setRequestFocusEnabled(false);
        txtMsj.setVerifyInputWhenFocusTarget(false);
        scrollDialogo.setViewportView(txtMsj);

        lblReaccion.setToolTipText("");
        lblReaccion.setMaximumSize(new java.awt.Dimension(108, 76));
        lblReaccion.setMinimumSize(new java.awt.Dimension(108, 76));
        lblReaccion.setPreferredSize(new java.awt.Dimension(108, 76));

        txtNombre.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                txtNombreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblReaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(scrollDialogo, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtNombre))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReaccion, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollDialogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAceptar, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addGap(21, 21, 21))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAceptarActionPerformed
    {//GEN-HEADEREND:event_btnAceptarActionPerformed
        Main.backend.getUsuario().setNombre(this.txtNombre.getText());
        this.isDialogResult = true;
        this.setVisible(false);
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_txtNombreActionPerformed
    {//GEN-HEADEREND:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel lblReaccion;
    private javax.swing.JScrollPane scrollDialogo;
    private javax.swing.JTextArea txtMsj;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
   // </editor-fold>
    //<editor-fold desc="Atributos">
    public boolean isDialogResult = false;

    public enum TipoRespuesta
    {
        Pista, GanaPartida, PierdePartidaSinPuntos, PierdePartidaConPuntos, SubeNivel, GanaJuego;
    }

    // </editor-fold>
    //<editor-fold desc="Constructores">
    public FormDialogo(java.awt.Frame parent, boolean modal, String texto, TipoRespuesta tipoRespuesta)
    {
        super(parent, modal);
        this.setContentPane(new JLabel(new ImageIcon("dialogo-12.png")));
        initComponents();
        reaccionesConDialogo(tipoRespuesta, texto);

        //pide ingresar nombre
        this.txtNombre.setText("Ingresá tu nombre");

        this.txtNombre.addFocusListener(new FocusListener()
        {
            @Override
            public void focusGained(FocusEvent e)
            {
                txtNombre.setText("");
            }

            @Override
            public void focusLost(FocusEvent e)
            {
                // throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });

    }

    // </editor-fold>    
    //<editor-fold desc="GetSet">
    public boolean isIsDialogResult()
    {
        return isDialogResult;
    }

    public void setIsDialogResult(boolean isDialogResult)
    {
        this.isDialogResult = isDialogResult;
    }

    //</editor-fold>
    //<editor-fold desc="Metodos">
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FormDialogo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FormDialogo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FormDialogo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FormDialogo.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                FormDialogo dialog = new FormDialogo(new javax.swing.JFrame(), true, null, TipoRespuesta.Pista);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    private void reaccionesConDialogo(TipoRespuesta tipoRespuesta, String texto)
    {
        this.txtMsj.setText(texto.toUpperCase());//TEXTO QUE VA A DECIR
        this.txtMsj.setOpaque(false);
        scrollDialogo.setBackground(new Color(0, 0, 0));
        scrollDialogo.setOpaque(false);
        scrollDialogo.getViewport().setOpaque(false);
        this.btnAceptar.setIcon(new ImageIcon("botones-13.png"));
        this.btnAceptar.setDisabledIcon(new ImageIcon("botones-14.png"));
        this.btnAceptar.setRolloverIcon(new ImageIcon("botones-14.png"));

        switch (tipoRespuesta)
        {
            case Pista:
                this.txtNombre.setVisible(false);
                this.lblReaccion.setIcon(new ImageIcon("108x76_05.jpg"));
                break;
            case GanaPartida:
                this.txtNombre.setVisible(false);
                this.lblReaccion.setIcon(new ImageIcon("108x76_15.jpg"));
                break;
            case PierdePartidaConPuntos:
                this.txtNombre.setVisible(true);
                this.lblReaccion.setIcon(new ImageIcon("108x76_06.jpg"));
                break;
            case PierdePartidaSinPuntos:
                this.txtNombre.setVisible(false);
                this.lblReaccion.setIcon(new ImageIcon("108x76_06.jpg"));
                break;
            case SubeNivel:
                this.txtNombre.setVisible(false);
                this.lblReaccion.setIcon(new ImageIcon("108x76_15.jpg"));
                break;
            case GanaJuego:
                this.txtNombre.setVisible(true);
                this.lblReaccion.setIcon(new ImageIcon("108x76_15.jpg"));
                break;
        }

    }
    // </editor-fold>
}
