/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import com.sun.javafx.scene.SceneHelper;

/**
 *
 * @author Nano
 */
public class FormConfig extends javax.swing.JDialog {

    /**
     * Creates new form FormConfig2
     */
    public FormConfig(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabConfig = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblRankCantidad = new javax.swing.JLabel();
        txtRankCantidad = new javax.swing.JTextField();
        lblDiccionarioCantidad = new javax.swing.JLabel();
        txtDiccionarioCantidad = new javax.swing.JTextField();
        btnIrConfigUsuarios = new javax.swing.JButton();
        btnIrConfigDiccionario = new javax.swing.JButton();
        btnVolverInicio = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("forms/Bundle"); // NOI18N
        setTitle(bundle.getString("titulo_config")); // NOI18N

        lblRankCantidad.setText("Cantidad Usuarios en Ranking:");

        txtRankCantidad.setPreferredSize(new java.awt.Dimension(20, 20));
        txtRankCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRankCantidadActionPerformed(evt);
            }
        });

        lblDiccionarioCantidad.setText("Cantidad Palabras en Diccionario:");

        txtDiccionarioCantidad.setPreferredSize(new java.awt.Dimension(20, 20));
        txtDiccionarioCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDiccionarioCantidadActionPerformed(evt);
            }
        });

        btnIrConfigUsuarios.setText("Configurar Usuarios");
        btnIrConfigUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrConfigUsuariosActionPerformed(evt);
            }
        });

        btnIrConfigDiccionario.setText("Configurar Diccionario");
        btnIrConfigDiccionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIrConfigDiccionarioActionPerformed(evt);
            }
        });

        btnVolverInicio.setText("Volver al Inicio");
        btnVolverInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRankCantidad)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDiccionarioCantidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(btnIrConfigDiccionario)
                            .addComponent(btnIrConfigUsuarios)
                            .addComponent(btnVolverInicio)))
                    .addComponent(txtDiccionarioCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRankCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtDiccionarioCantidad, txtRankCantidad});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRankCantidad)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtRankCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblDiccionarioCantidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDiccionarioCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnIrConfigUsuarios)
                        .addGap(43, 43, 43)
                        .addComponent(btnIrConfigDiccionario)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 144, Short.MAX_VALUE)
                .addComponent(btnVolverInicio)
                .addGap(11, 11, 11))
        );

        tabConfig.addTab("Inicio Configuración", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );

        tabConfig.addTab("Ranking Usuarios", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 527, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 297, Short.MAX_VALUE)
        );

        tabConfig.addTab("Palabras en Diccionario", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabConfig)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tabConfig)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtRankCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRankCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRankCantidadActionPerformed

    private void txtDiccionarioCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDiccionarioCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDiccionarioCantidadActionPerformed

    private void btnIrConfigUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrConfigUsuariosActionPerformed
        this.tabConfig.setSelectedIndex(1);
    }//GEN-LAST:event_btnIrConfigUsuariosActionPerformed

    private void btnIrConfigDiccionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrConfigDiccionarioActionPerformed
        this.tabConfig.setSelectedIndex(2);
    }//GEN-LAST:event_btnIrConfigDiccionarioActionPerformed

    private void btnVolverInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverInicioActionPerformed
        this.getParent().setVisible(Boolean.TRUE);
        this.dispose();

    }//GEN-LAST:event_btnVolverInicioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormConfig.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FormConfig dialog = new FormConfig(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIrConfigDiccionario;
    private javax.swing.JButton btnIrConfigUsuarios;
    private javax.swing.JButton btnVolverInicio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblDiccionarioCantidad;
    private javax.swing.JLabel lblRankCantidad;
    private javax.swing.JTabbedPane tabConfig;
    private javax.swing.JTextField txtDiccionarioCantidad;
    private javax.swing.JTextField txtRankCantidad;
    // End of variables declaration//GEN-END:variables
}
