/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ahorcado.Forms;

import ahorcado.Ahorcado;
import ahorcado.Enumerados.Dificultad;
import ahorcado.Excepciones.GanaJuego;
import ahorcado.Main;
import java.awt.Container;
import java.awt.GridLayout;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import sun.swing.BakedArrayList;

/**
 *
 * @author Nano
 */
public class FormInicial extends javax.swing.JFrame
{
    //<editor-fold defaultstate="collapsed" desc="Atributos">
    FormEligeNivel formNivel;
    PanelUsuario panelUsuario;
    Container contenedor;
    ComponentListener listenerVolverAInicio;

    //</editor-fold>
    /**
     * Creates new form FormInicial
     */
    public FormInicial()
    {
        initComponents();
        formNivel = new FormEligeNivel(this, true);
        formNivel.setLocationRelativeTo(null);
        panelUsuario = new PanelUsuario();
        contenedor = new Container();
        listenerVolverAInicio = new ComponentListener()
        {
            @Override
            public void componentResized(ComponentEvent e)
            {

            }

            @Override
            public void componentMoved(ComponentEvent e)
            {

            }

            @Override
            public void componentShown(ComponentEvent e)
            {

            }

            @Override
            public void componentHidden(ComponentEvent e)
            {
                jpInicio.setVisible(true);
                jpGameplay.setVisible(false);
                jpUsuario.setVisible(false);
                jpRank.setVisible(false);
            }
        };
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jpInicio = new javax.swing.JPanel();
        btnJugar = new javax.swing.JButton();
        jpGameplay = new javax.swing.JPanel();
        jpUsuario = new javax.swing.JPanel();
        jpRank = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        mnMenu = new javax.swing.JMenu();
        mnItemNuevo = new javax.swing.JMenuItem();
        mnItemRank = new javax.swing.JMenuItem();
        mnItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ahorcado"); // NOI18N
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(800, 600));

        jpInicio.setAlignmentX(0.0F);
        jpInicio.setAlignmentY(0.0F);
        jpInicio.setMaximumSize(null);
        jpInicio.setPreferredSize(new java.awt.Dimension(800, 600));

        btnJugar.setText("JUGAR");
        btnJugar.setAlignmentY(0.0F);
        btnJugar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnJugarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpInicioLayout = new javax.swing.GroupLayout(jpInicio);
        jpInicio.setLayout(jpInicioLayout);
        jpInicioLayout.setHorizontalGroup(
            jpInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpInicioLayout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addComponent(btnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(262, Short.MAX_VALUE))
        );
        jpInicioLayout.setVerticalGroup(
            jpInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpInicioLayout.createSequentialGroup()
                .addContainerGap(340, Short.MAX_VALUE)
                .addComponent(btnJugar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166))
        );

        jpGameplay.setAlignmentX(0.0F);
        jpGameplay.setAlignmentY(0.0F);
        jpGameplay.setMaximumSize(null);
        jpGameplay.setPreferredSize(new java.awt.Dimension(800, 600));

        javax.swing.GroupLayout jpGameplayLayout = new javax.swing.GroupLayout(jpGameplay);
        jpGameplay.setLayout(jpGameplayLayout);
        jpGameplayLayout.setHorizontalGroup(
            jpGameplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        jpGameplayLayout.setVerticalGroup(
            jpGameplayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpUsuarioLayout = new javax.swing.GroupLayout(jpUsuario);
        jpUsuario.setLayout(jpUsuarioLayout);
        jpUsuarioLayout.setHorizontalGroup(
            jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jpUsuarioLayout.setVerticalGroup(
            jpUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jpRank.setMaximumSize(null);

        javax.swing.GroupLayout jpRankLayout = new javax.swing.GroupLayout(jpRank);
        jpRank.setLayout(jpRankLayout);
        jpRankLayout.setHorizontalGroup(
            jpRankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jpRankLayout.setVerticalGroup(
            jpRankLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        mnMenu.setMnemonic('J');
        mnMenu.setText("Juego");

        mnItemNuevo.setMnemonic('N');
        mnItemNuevo.setText("Nuevo");
        mnItemNuevo.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnItemNuevoActionPerformed(evt);
            }
        });
        mnMenu.add(mnItemNuevo);

        mnItemRank.setMnemonic('R');
        mnItemRank.setText("Ranking");
        mnItemRank.setToolTipText("");
        mnItemRank.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnItemRankActionPerformed(evt);
            }
        });
        mnMenu.add(mnItemRank);

        mnItemSalir.setMnemonic('S');
        mnItemSalir.setText("Salir");
        mnItemSalir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                mnItemSalirActionPerformed(evt);
            }
        });
        mnMenu.add(mnItemSalir);

        menuBar.add(mnMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpGameplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpRank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpGameplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jpRank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnItemSalirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnItemSalirActionPerformed
    {//GEN-HEADEREND:event_mnItemSalirActionPerformed
        System.exit(NORMAL);
    }//GEN-LAST:event_mnItemSalirActionPerformed

    private void mnItemNuevoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnItemNuevoActionPerformed
    {//GEN-HEADEREND:event_mnItemNuevoActionPerformed
        //llama al evento de presionar btnJugar
        btnJugarActionPerformed(evt);
    }//GEN-LAST:event_mnItemNuevoActionPerformed

    private void mnItemRankActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_mnItemRankActionPerformed
    {//GEN-HEADEREND:event_mnItemRankActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnItemRankActionPerformed

    private void btnJugarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnJugarActionPerformed
    {//GEN-HEADEREND:event_btnJugarActionPerformed

        //pedir usuario
        pedirUsuario();

        //pedir dificultad
        //pedirDificultad();
        try
        {
            //llamar a nueva partida
            Main.backend.nuevoJuego(Main.backend.getUsuario(), Main.backend.getDificultad());
        }
        catch (GanaJuego ex)
        {
            //CARTELITO de que gano
        }
//jdContenedor.add(jpGameplay);
//jpGameplay.setVisible(true);
    }//GEN-LAST:event_btnJugarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(FormInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(FormInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(FormInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(FormInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new FormInicial().setVisible(true);
            }
        });
    }

    public void pedirUsuario()
    {
        panelUsuario.addComponentListener(listenerVolverAInicio);

        //limpiar contenedor
        if (contenedor != null)
        {
            contenedor.removeAll();
        }
        contenedor = jpUsuario;
        panelUsuario.addComponentListener(listenerVolverAInicio);
        contenedor.setLayout(new GridLayout(1, 1));
        contenedor.add(panelUsuario);
        jpUsuario.setVisible(true);
        panelUsuario.setVisible(true);
        jpInicio.setVisible(false);
    }

    public void pedirDificultad()
    {
        formNivel.setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnJugar;
    private javax.swing.JPanel jpGameplay;
    private javax.swing.JPanel jpInicio;
    private javax.swing.JPanel jpRank;
    private javax.swing.JPanel jpUsuario;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem mnItemNuevo;
    private javax.swing.JMenuItem mnItemRank;
    private javax.swing.JMenuItem mnItemSalir;
    private javax.swing.JMenu mnMenu;
    // End of variables declaration//GEN-END:variables
}
