/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ahorcado.Forms;

import ahorcado.Clases.Usuario;
import ahorcado.Main;

/**
 *
 * @author Nano
 */
public class PanelUsuario extends javax.swing.JPanel
{

    /**
     * Creates new form PanelUsuario
     */
    public PanelUsuario()
    {
        initComponents();
        for (Usuario u : Main.backend.getRanking().getListaDeUsuarios())
        {
            jcomboUsuario.addItem(u.getNombre());
        }
        setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        txtTitulo = new javax.swing.JTextField();
        scrollStats = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jcomboUsuario = new javax.swing.JComboBox<>();

        txtTitulo.setText("SELECCION DE USUARIO");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        scrollStats.setViewportView(jTextArea1);

        jcomboUsuario.setToolTipText("Ingrese su nombre");
        jcomboUsuario.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jcomboUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcomboUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollStats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollStats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jcomboUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jcomboUsuarioActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jcomboUsuarioActionPerformed
    {//GEN-HEADEREND:event_jcomboUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcomboUsuarioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox<String> jcomboUsuario;
    private javax.swing.JScrollPane scrollStats;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
